### ISSUE TITLE
Use the new official MorphoLibJ logo

### ISSUE THREAD

**Issue by tinevez** [trackmate-sc/TrackMate-MorphoLibJ#2]
https://github.com/ijpb/MorphoLibJ/blob/master/doc/logo/logo-64x64.png

@dlegland do you have a pdf or svg version so that I could mint it with the TrackMate logo?

**Comment by dlegland** [comment]
Hi Jean-Yves!
I just pushed SVG versions of the logos, together with new images at different resolutions. Hope you will find what you need!
David
